import React from 'react';

// Centralized mock for MUI icons to reduce test boilerplate and improve performance
const iconNameMap: Record<string, string> = {
    MenuRounded: 'menu',
    LocationOn: 'location',
    ViewModuleRounded: 'view-module',
    NavigateBeforeRounded: 'navigate-before',
    NavigateNextRounded: 'navigate-next',
    PlayArrowRounded: 'play-arrow',
    PauseRounded: 'pause',
    FirstPageRounded: 'first-page',
    LastPageRounded: 'last-page',
    KeyboardArrowUpRounded: 'keyboard-arrow-up',
    KeyboardArrowDownRounded: 'keyboard-arrow-down',
    KeyboardArrowLeftRounded: 'keyboard-arrow-left',
    KeyboardArrowRightRounded: 'keyboard-arrow-right',
    CircleRounded: 'circle',
    InfoRounded: 'info',
    GridView: 'grid-view',
    TextFieldsRounded: 'text-fields-rounded',
    CodeRounded: 'code-rounded',
    DataArrayRounded: 'data-array',
    PlusOneRounded: 'plus-one',
    BarChartRounded: 'bar-chart',
    ShowChartRounded: 'show-chart',
    AnalyticsRounded: 'analytics',
    TrendingUpRounded: 'trending-up',
    AttachMoneyRounded: 'attach-money',
    BusinessRounded: 'business',
    SettingsRounded: 'settings',
    ArrowForward: 'arrow-forward',
};

const mockIcons = [
    'MenuRounded',
    'GitHub',
    'Code',
    'Cloud',
    'Psychology',
    'Work',
    'Email',
    'Phone',
    'LocationOn',
    'OpenInNew',
    'ArrowForward',
    'HomeRounded',
    'CloseRounded',
    'GamepadRounded',
    'ViewModuleRounded',
    'Refresh',
    'NavigateBeforeRounded',
    'NavigateNextRounded',
    'PlayArrowRounded',
    'PauseRounded',
    'FirstPageRounded',
    'LastPageRounded',
    'KeyboardArrowUpRounded',
    'KeyboardArrowDownRounded',
    'KeyboardArrowLeftRounded',
    'KeyboardArrowRightRounded',
    'CircleRounded',
    'KeyboardArrowDown',
    'Calculate',
    'Replay',
    'InfoRounded',
    'GridView',
    'TextFields',
    'TextFieldsRounded',
    'CodeRounded',
    'DataArrayRounded',
    'PlusOneRounded',
    'BarChartRounded',
    'ShowChartRounded',
    'AnalyticsRounded',
    'TrendingUpRounded',
    'AttachMoneyRounded',
    'BusinessRounded',
    'SettingsRounded',
].reduce((acc, iconName) => {
    const testId = iconNameMap[iconName] || iconName.toLowerCase();
    acc[iconName] = () => <div data-testid={`${testId}-icon`}>{iconName}</div>;
    return acc;
}, {} as any);

module.exports = mockIcons;
